FROM apache/airflow:2.9.1-python3.11

ARG AIRFLOW_VERSION=2.9.1

USER root

RUN apt-get update \
    && apt-get install --yes --no-install-recommends git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY --chown=airflow:root requirements-airflow.txt /opt/airflow/requirements-airflow.txt

RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    --requirement /opt/airflow/requirements-airflow.txt