version: 2

sources:
  - name: monitoring_data
    description: "Métriques techniques produites par Airflow."
    schema: schema_monitoring

    tables:
      - name: ingestion_runs
        description: "Une ligne par exécution d’ingestion Vélib."

        columns:
          - name: run_id
            tests:
              - unique
              - not_null

          - name: status
            tests:
              - not_null

          - name: started_at
            tests:
              - not_null