version: 2

models:
  - name: fct_velib_status
    description: >-
      Table de faits historisée contenant une ligne par station
      et par horodatage métier Vélib.

    columns:
      - name: observation_id
        description: >-
          Clé technique déterministe construite à partir de
          station_id et status_updated_at.
        tests:
          - unique
          - not_null

      - name: station_id
        description: "Identifiant de la station Vélib."
        tests:
          - not_null

      - name: station_name
        description: "Nom de la station."
        tests:
          - not_null

      - name: total_capacity
        description: "Capacité totale déclarée par l’API."
        tests:
          - not_null

      - name: status_updated_at
        description: "Horodatage métier de l’observation."
        tests:
          - not_null

      - name: station_status
        description: "Statut catégorisé de la station."
        tests:
          - not_null
          - accepted_values:
              values:
                - "Normal"
                - "Presque pleine"
                - "Presque vide"
                - "Vide"
                - "Hors service"
                - "Non installée"