slice_name: "\xC9volution quotidienne du d\xE9bit routier"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 5__table
  viz_type: echarts_timeseries_line
  x_axis: observation_date
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: "SUM(\n    average_vehicle_flow\n    * vehicle_flow_observation_count\n\
      )\n/\nNULLIF(\n    SUM(vehicle_flow_observation_count),\n    0\n)"
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "D\xE9bit moyen quotidien"
    optionName: metric_hpgi99zzpj5_mw7d5v92mdd
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: observation_date
    operator: TEMPORAL_RANGE
    comparator: Last month
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_qw4t925bgdo_nxzhd6zkzur
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: Date
  x_axis_title_margin: 30
  y_axis_title: "V\xE9hicules par heure"
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerEnabled: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 4
query_context: "{\"datasource\":{\"id\":5,\"type\":\"table\"},\"force\":false,\"queries\"\
  :[{\"filters\":[{\"col\":\"observation_date\",\"op\":\"TEMPORAL_RANGE\",\"val\"\
  :\"Last month\"}],\"extras\":{\"time_grain_sqla\":\"P1D\",\"having\":\"\",\"where\"\
  :\"\"},\"applied_time_extras\":{},\"columns\":[{\"timeGrain\":\"P1D\",\"columnType\"\
  :\"BASE_AXIS\",\"sqlExpression\":\"observation_date\",\"label\":\"observation_date\"\
  ,\"expressionType\":\"SQL\"}],\"metrics\":[{\"expressionType\":\"SQL\",\"sqlExpression\"\
  :\"SUM(\\n    average_vehicle_flow\\n    * vehicle_flow_observation_count\\n)\\\
  n/\\nNULLIF(\\n    SUM(vehicle_flow_observation_count),\\n    0\\n)\",\"column\"\
  :null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"\
  label\":\"D\xE9bit moyen quotidien\",\"optionName\":\"metric_hpgi99zzpj5_mw7d5v92mdd\"\
  }],\"orderby\":[[{\"expressionType\":\"SQL\",\"sqlExpression\":\"SUM(\\n    average_vehicle_flow\\\
  n    * vehicle_flow_observation_count\\n)\\n/\\nNULLIF(\\n    SUM(vehicle_flow_observation_count),\\\
  n    0\\n)\",\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"D\xE9bit moyen quotidien\",\"optionName\":\"metric_hpgi99zzpj5_mw7d5v92mdd\"\
  },false]],\"annotation_layers\":[],\"row_limit\":10000,\"series_columns\":[],\"\
  series_limit\":0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"custom_form_data\"\
  :{},\"time_offsets\":[],\"post_processing\":[{\"operation\":\"pivot\",\"options\"\
  :{\"index\":[\"observation_date\"],\"columns\":[],\"aggregates\":{\"D\xE9bit moyen\
  \ quotidien\":{\"operator\":\"mean\"}},\"drop_missing_columns\":false}},{\"operation\"\
  :\"flatten\"}]}],\"form_data\":{\"datasource\":\"5__table\",\"viz_type\":\"echarts_timeseries_line\"\
  ,\"x_axis\":\"observation_date\",\"time_grain_sqla\":\"P1D\",\"x_axis_sort_asc\"\
  :true,\"x_axis_sort_series\":\"name\",\"x_axis_sort_series_ascending\":true,\"metrics\"\
  :[{\"expressionType\":\"SQL\",\"sqlExpression\":\"SUM(\\n    average_vehicle_flow\\\
  n    * vehicle_flow_observation_count\\n)\\n/\\nNULLIF(\\n    SUM(vehicle_flow_observation_count),\\\
  n    0\\n)\",\"column\":null,\"aggregate\":null,\"datasourceWarning\":false,\"hasCustomLabel\"\
  :true,\"label\":\"D\xE9bit moyen quotidien\",\"optionName\":\"metric_hpgi99zzpj5_mw7d5v92mdd\"\
  }],\"groupby\":[],\"adhoc_filters\":[{\"expressionType\":\"SIMPLE\",\"subject\"\
  :\"observation_date\",\"operator\":\"TEMPORAL_RANGE\",\"comparator\":\"Last month\"\
  ,\"clause\":\"WHERE\",\"sqlExpression\":null,\"isExtra\":false,\"isNew\":false,\"\
  datasourceWarning\":false,\"filterOptionName\":\"filter_qw4t925bgdo_nxzhd6zkzur\"\
  }],\"order_desc\":true,\"row_limit\":10000,\"truncate_metric\":true,\"show_empty_columns\"\
  :true,\"comparison_type\":\"values\",\"annotation_layers\":[],\"forecastPeriods\"\
  :10,\"forecastInterval\":0.8,\"x_axis_title\":\"Date\",\"x_axis_title_margin\":30,\"\
  y_axis_title\":\"V\xE9hicules par heure\",\"y_axis_title_margin\":30,\"y_axis_title_position\"\
  :\"Left\",\"sort_series_type\":\"sum\",\"color_scheme\":\"supersetColors\",\"seriesType\"\
  :\"line\",\"only_total\":true,\"opacity\":0.2,\"markerEnabled\":true,\"markerSize\"\
  :6,\"show_legend\":true,\"legendType\":\"scroll\",\"legendOrientation\":\"top\"\
  ,\"x_axis_time_format\":\"smart_date\",\"rich_tooltip\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"y_axis_format\":\"SMART_NUMBER\",\"truncateXAxis\":true,\"y_axis_bounds\"\
  :[null,null],\"extra_form_data\":{},\"dashboards\":[4],\"force\":false,\"result_format\"\
  :\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"result_type\":\"\
  full\"}"
cache_timeout: null
uuid: bd5116f7-d543-45e0-92e2-ba7fa1fa6801
version: 1.0.0
dataset_uuid: 2e7359c1-821d-4dc2-9b71-641c79fa2003
